// Programme de départ : « Busy Girl » (phase 1 saisie d'après les captures, phase 2 à venir).
// Une séance = { name, duration, description, objective, muscles[], equipment[], exercises[] }
// Un exercice = { name, group, sets, reps, perSide }  (reps = texte libre : "12", "8-10", "30 sec", "15-20 min")
(function () {
  let n = 0;
  const id = () => 's' + (++n).toString(36);
  const ex = (group, name, sets, reps, perSide = false) => ({ id: id(), group, name, sets, reps, perSide });

  const WARM = 'Échauffement';
  const warmupLower = (catCowPerSide) => [
    ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
    ex(WARM, 'Deep Lunges Dynamiques', 1, '5', true),
    ex(WARM, 'Ouverture de Hanches', 1, '10', true),
    ex(WARM, 'Leg Swing Frontal', 1, '10', true),
    ex(WARM, 'Cat Cow', 1, '5', catCowPerSide),
  ];

  const sessions = [
    {
      id: id(), name: 'Booty Shape & Cardio', duration: 40,
      description: "Une séance ciblée sur les fessiers pour renforcer et développer le bas du corps, avec un travail complet des muscles fessiers. En option si tu en as le temps et l'envie, termine avec 15 à 20 min de marche inclinée sur le tapis. Si tu t'entraînes à la maison, tu peux aller marcher en extérieur.",
      objective: 'Renforcer les fessiers et les ischio-jambiers tout en améliorant la stabilité des hanches et du tronc.',
      muscles: ['Fessiers', 'Bas du corps', 'Ischios', 'Quadriceps'],
      equipment: ['Abducteur machine', 'Banc', 'Box/step', 'Disque', 'Machine hip thrust', 'Smith machine'],
      exercises: [
        ...warmupLower(false),
        ex('Exercice 1', 'Abductions', 2, '15-20'),
        ex('Exercice 2', 'Hip Thrust - Machine', 3, '12'),
        ex('Exercice 3', 'Fentes Bulgares - Smith Machine', 2, '10', true),
        ex('Exercice 4', 'Glute Hyperextension - Disque', 2, '12-15'),
        ex('Exercice 5', 'Marche Inclinée Modérée 4% ou Dehors (optionnel)', 1, '15-20 min'),
      ],
    },
    {
      id: id(), name: 'Upper Pilates & Abs', duration: 35,
      description: "Une séance complète axée sur le haut du corps, la mobilité et le renforcement de la sangle abdominale, avec un travail du dos et des triceps suivi de circuits ciblant le haut du corps, les lombaires et les abdominaux.",
      objective: 'Renforcer le haut du corps, améliorer sa force et la stabilité du tronc.',
      muscles: ['Abs', 'Bras', 'Dos', 'Haut du corps', 'Dorsaux'],
      equipment: ['Banc', 'Élastique', 'Haltère', 'Poulie', 'Tapis de sol'],
      exercises: [
        ex(WARM, 'Chien Tête en Bas et Cobra Pose', 1, '10'),
        ex(WARM, 'Cat Cow', 1, '5'),
        ex(WARM, 'Avant Arrière', 1, '10'),
        ex(WARM, 'Around The World', 1, '5', true),
        ex('Exercice 1', 'Tirage Vertical - Prise Large', 3, '12'),
        ex('Exercice 2 - Superset', 'Triceps Extensions Overhead - Haltère', 3, '12'),
        ex('Exercice 2 - Superset', 'Around The World - Haltères', 3, '10'),
        ex('Exercice 3', 'Cobra Stretch', 3, '8'),
        ex('Exercice 3', 'Arm Raise au Sol', 3, '8'),
        ex('Exercice 3', 'Around The World Raise', 3, '8'),
        ex('Exercice 3', 'Superman Dynamique', 3, '8'),
        ex('Exercice 3', 'Superman Hold', 3, '20 sec'),
        ex('Exercice 4', 'Glute Bridge Marche - Haltère', 3, '30 sec'),
        ex('Exercice 4', 'Sit Ups - Haltère', 3, '30 sec'),
        ex('Exercice 4', 'Dead Bug - Haltère', 3, '30 sec'),
        ex('Exercice 4', 'Hollow Hold', 3, '30 sec'),
      ],
    },
    {
      id: id(), name: 'Booty Tone & Cardio', duration: 40,
      description: "Une séance ciblée sur l'ensemble du bas du corps, avec un travail complet. En option si tu as le temps et l'envie, termine avec 15 à 20 min de stairmaster (remplaçable par de la marche sur tapis). Si tu t'entraînes à la maison, tu peux aller marcher en extérieur.",
      objective: 'Tonification, Perte de Poids',
      muscles: ['Glutes', 'Bas du corps', 'Fessiers', 'Ischio-jambiers', 'Quadriceps'],
      equipment: ['Disque', 'Haltère', 'Machine hip thrust', 'Poulie', 'Stairmaster'],
      exercises: [
        ...warmupLower(true),
        ex('Exercice 1', 'Hip Thrust - Machine', 3, '8-10'),
        ex('Exercice 2 - Superset', 'Romanian Deadlift - Haltères', 3, '10-12'),
        ex('Exercice 2 - Superset', 'Sumo Squat - Haltère', 3, '12-15'),
        ex('Exercice 3', 'Step Up - Haltère', 2, '10', true),
        ex('Exercice 4', 'Kick Back - Poulie', 2, '12', true),
        ex('Exercice 5', 'Stairmaster ou Marche Dehors (optionnel)', 1, '15-20 min'),
      ],
    },
    {
      id: id(), name: 'Cardio & Abs', duration: 45,
      description: "Améliore ton cardio grâce à la marche et renforce ta sangle abdominale avec un circuit de gainage. Dans cette séance, la marche sur tapis peut être remplacée par de la marche en extérieur, notamment si tu t'entraînes à la maison.",
      objective: 'Tonification, Perte de Poids',
      muscles: ['Abs', 'Full body', 'Cardio'],
      equipment: ['Haltère', 'Tapis de course', 'Tapis de sol'],
      exercises: [
        ex('Exercice 1', 'Marche Inclinée Modérée 2% ou Dehors', 1, '35-45 min'),
        ex('Exercice 2', 'Rolling Plank', 3, '30 sec'),
        ex('Exercice 2', 'Side Plank Crunch Raise Droit - Haltère', 3, '30 sec', true),
        ex('Exercice 2', 'Side Plank Crunch Raise Gauche - Haltère', 3, '30 sec', true),
        ex('Exercice 2', 'Plank', 3, '30 sec'),
      ],
    },
  ];


  // ───── Phase 2 (captures reçues ; muscles/matériel partiellement coupés → à compléter si besoin) ─────
  const sessions2 = [
    {
      id: id(), name: 'Booty Sculpt & Cardio', duration: 40,
      description: "Renforce et sculpte avec efficacité ton bas du corps. Travaille les fessiers et abducteurs, suivis de quelques minutes de marche inclinée. Si tu t'entraînes à la maison, tu peux aller marcher en extérieur.",
      objective: 'Renforcer les fessiers et les ischio-jambiers tout en améliorant la stabilité des hanches et du tronc.',
      muscles: ['Glutes', 'Bas du corps', 'Fessiers', 'Ischios jambiers', 'Mollets'],
      equipment: ['Banc', 'Box/step', 'Disque', 'Haltère', 'Smith machine'],
      exercises: [
        ...warmupLower(false),
        ex('Exercice 1', 'Hip Thrust Unilatéral - Haltère', 3, '8-10', true),
        ex('Exercice 2', 'Romanian Deadlift - Smith Machine', 3, '12'),
        ex('Exercice 3', 'Fentes Bulgares - Smith Machine', 2, '10', true),
        ex('Exercice 4', 'Leg Abduction Au Sol - Poids', 2, '12-15', true),
        ex('Exercice 5', 'Marche Inclinée Modérée 4% ou Dehors (optionnel)', 1, '15-20 min'),
      ],
    },
    {
      id: id(), name: 'Upper Pilates & Core', duration: 35,
      description: 'Sculpte ton haut du corps et renforce ta sangle abdominale !',
      objective: 'Renforcer le haut du corps, améliorer sa force et la stabilité du tronc.',
      muscles: ['Abs', 'Bras', 'Dos', 'Bas du corps', 'Haut du corps'],
      equipment: ['Barre libre', 'Haltère', 'Tapis de sol', 'Cage de musculation'],
      exercises: [
        ex(WARM, 'Chien Tête en Bas et Cobra Pose', 1, '5'),
        ex(WARM, 'Cat Cow', 1, '5'),
        ex(WARM, 'Avant Arrière', 1, '10'),
        ex(WARM, 'Around The World', 1, '5', true),
        ex('Exercice 1', 'Australian Row', 3, '10'),
        ex('Exercice 2 - Superset', 'Shoulder Press Unilatéral - Haltères', 3, '10', true),
        ex('Exercice 2 - Superset', 'Biceps Curl Alternés - Haltères', 3, '10', true),
        ex('Exercice 3', 'Plank Row - Haltères', 3, '10'),
        ex('Exercice 3', 'Pompes', 3, '8-10'),
        ex('Exercice 3', 'Triceps Au Sol - Haltère', 3, '8', true),
        ex('Exercice 4', 'High Bridge Marches', 3, '30 sec'),
        ex('Exercice 4', 'Side Plank Crunch Raise Droit - Haltère', 3, '30 sec'),
        ex('Exercice 4', 'Side Plank Crunch Raise Gauche - Haltère', 3, '30 sec'),
        ex('Exercice 4', 'Hollow Hold Dynamique', 3, '30 sec'),
      ],
    },
    {
      id: id(), name: 'Booty Power & Cardio', duration: 40,
      description: "Sollicite le bas du corps, apporte force et tonicité à tes fessiers. En option de cette séance, tu peux terminer avec 15 à 20 min de stairmaster (remplaçable par de la marche sur tapis). Si tu t'entraînes à la maison tu peux aller marcher en extérieur.",
      objective: 'Tonification, Perte de Poids',
      muscles: ['Abs', 'Glutes', 'Bas du corps', 'Fessiers', 'Ischios'],
      equipment: ['Banc', 'Disque', 'Machine hip thrust', 'Poulie', 'Smith machine', 'Stairmaster'],
      exercises: [
        ...warmupLower(false),
        ex('Exercice 1', 'Hip Thrust - Machine', 3, '8-10'),
        ex('Exercice 2', 'Good Morning - Smith Machine', 3, '10-12'),
        ex('Exercice 3', 'Step Up - Poulie', 2, '10', true),
        ex('Exercice 4', 'Kick Back - Poulie', 2, '12', true),
        ex('Exercice 5', 'Stairmaster ou Marche Dehors (optionnel)', 1, '15-20 min'),
      ],
    },
    {
      id: id(), name: 'Cardio Burn & Abs', duration: 45,
      description: "Dynamise ton corps grâce à la marche inclinée et renforce les muscles de la sangle abdominale. Une séance parfaite pour améliorer tes performances et te tonifier. Dans cette séance, la marche sur tapis peut être remplacée par de la marche en extérieur, notamment si tu t'entraînes à la maison.",
      objective: 'Tonification, Perte de Poids',
      muscles: ['Abs', 'Full body', 'Cardio'],
      equipment: ['Tapis de course', 'Tapis de sol'],
      exercises: [
        ex('Exercice 1', 'Marche Inclinée Modérée 6% ou Dehors', 1, '35-45 min'),
        ex('Exercice 2', 'Bear In & Outs', 3, '30 sec'),
        ex('Exercice 2', 'Bear Knee Taps', 3, '30 sec'),
        ex('Exercice 2', 'Pike To Plank', 3, '30 sec'),
        ex('Exercice 2', 'Plank', 3, '30 sec'),
      ],
    },
  ];

  // ───── Build At Home (phase 1 « Débutante » d'après les captures ; phase 2 à venir) ─────
  const bahSessions = [
    {
      id: id(), name: 'Juicy Glute Débutante', duration: 40,
      description: 'Séance du programme Maison Build At Home Débutante',
      objective: 'Force et Flexibilité',
      muscles: ['Fessiers'],
      equipment: ['Bande de résistance', 'Haltère', 'Tapis de sol', 'Chaise'],
      exercises: [
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Deep Lunges Dynamiques', 1, '5', true),
        ex(WARM, 'Ouverture de Hanches', 1, '10', true),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '15'),
        ex(WARM, 'Glute Bridge - PDC', 1, '15'),
        ex('Exercice 1 - Superset', 'Hip Thrust - Bande de Résistance', 4, '10'),
        ex('Exercice 1 - Superset', 'Hip Thrust - PDC', 4, '12'),
        ex('Exercice 2', 'Romanian Deadlift - Haltères', 3, '12'),
        ex('Exercice 3', 'Fentes Bulgares - Haltères', 3, '8', true),
        ex('Exercice 4', 'Sumo Squat - Haltère', 3, '12'),
        ex('Exercice 5 - Superset', 'Kick Back - Bande de Résistance', 2, '10', true),
        ex('Exercice 5 - Superset', 'Leg Abduction - Bande De Résistance', 2, '10', true),
      ],
    },
    {
      id: id(), name: 'Abs & Upper Sculpt Débutante', duration: 31,
      description: 'Séance Haut du Corps Débutant du Programme Maison Build At Home',
      objective: 'Force et Flexibilité',
      muscles: ['Abs', 'Haut du corps'],
      equipment: ['Haltère', 'Tapis de sol', 'Chaise'],
      exercises: [
        ex(WARM, 'Chien Tête en Bas', 1, '5'),
        ex(WARM, 'Cat Cow', 1, '5'),
        ex(WARM, 'Around The World', 1, '10'),
        ex(WARM, 'Pull Apart', 1, '10'),
        ex('Exercice 1 - Superset', 'Développé Couché au Sol - Haltères', 3, '10'),
        ex('Exercice 1 - Superset', 'Rowing - Haltères', 3, '10'),
        ex('Exercice 2 - Superset', 'Biceps Curl - Haltères', 3, '10'),
        ex('Exercice 2 - Superset', 'Triceps Extensions Inclinés - Haltères', 3, '10'),
        ex('Exercice 3', 'Élévations Latérales - Haltères', 3, '12'),
        ex('Exercice 4', 'Gainage Planche', 3, '30 sec'),
        ex('Exercice 4', 'Gainage Latéral Droit', 3, '30 sec'),
        ex('Exercice 4', 'Gainage Latéral Gauche', 3, '30 sec'),
        ex('Exercice 4', 'In & Outs', 3, '30 sec'),
      ],
    },
    {
      id: id(), name: 'Ultimate Booty Débutante', duration: 45,
      description: 'Séance Fessier du Programme Maison Build At Home',
      objective: 'Prise de Masse, Perte de Poids, Tonification',
      muscles: ['Bas du corps', 'Fessiers'],
      equipment: ['Bande de résistance', 'Haltère', 'Tapis de sol', 'Chaise'],
      exercises: [
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Deep Lunges Dynamiques', 1, '5', true),
        ex(WARM, 'Ouverture de Hanches', 1, '10', true),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '15'),
        ex(WARM, 'Glute Bridge - PDC', 1, '10'),
        ex('Exercice 1', 'Goblet Squat - Haltère', 3, '10'),
        ex('Exercice 2', 'Step Up - Haltère', 3, '10', true),
        ex('Exercice 3', 'Sliding Reverse Leg Curl', 3, '8'),
        ex('Exercice 4 - Triset', 'Glute Bridge - Bande de Résistance', 4, '10'),
        ex('Exercice 4 - Triset', 'Glute Bridge Pulses - PDC', 4, '10'),
        ex('Exercice 4 - Triset', 'Glute Bridge Pause - PDC', 4, '20 sec'),
        ex('Exercice 5', 'Sumo Squat Pulses - Bande de Résistance', 2, 'AMRAP'),
      ],
    },
    {
      id: id(), name: 'Heart Rate Débutante', duration: 40,
      description: 'Séance Cardio Débutante du Programme Maison Build At Home',
      objective: 'Amélioration des Performances',
      muscles: ['Full body', 'Cardio'],
      equipment: ['Tapis de sol'],
      exercises: [
        ex(WARM, 'Cat Cow', 1, '5'),
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '10'),
        ex('Exercice 1', 'Fentes Croisées Alternées - PDC', 4, '30 sec'),
        ex('Exercice 1', 'Jump Squat', 4, '30 sec'),
        ex('Exercice 1', 'Mountain Climber', 4, '30 sec'),
        ex('Exercice 1', 'Mountain Climber Lent', 4, '30 sec'),
        ex('Exercice 1', 'Gainage Planche', 4, '30 sec'),
        ex('Exercice 1', 'Glute Bridge - PDC', 4, '30 sec'),
        ex('Exercice 1', 'Demi Burpees', 4, '30 sec'),
        ex('Exercice 1', 'Planche Haute Tap Pieds', 4, '30 sec'),
        ex('Exercice 1', 'Sit Ups', 4, '30 sec'),
      ],
    },
    {
      id: id(), name: 'Body Mastery Débutante', duration: 40,
      description: 'Séance Débutante Full Body Du Programme Maison Build At Home',
      objective: 'Tonification, Perte de Poids',
      muscles: ['Full body'],
      equipment: ['Bande de résistance', 'Haltère', 'Tapis de sol'],
      exercises: [
        ex(WARM, 'Chien Tête En Bas Et Cobra Pose', 1, '5'),
        ex(WARM, 'Side to Side Reach', 1, '10'),
        ex(WARM, 'Around The World', 1, '10'),
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '10'),
        ex('Exercice 1', 'Squat en Développé Militaire - Haltères', 3, '10'),
        ex('Exercice 2', 'Romanian Deadlift en Rowing - Haltères', 3, '10'),
        ex('Exercice 3', 'Donkey Kick Row - Haltère', 3, '8', true),
        ex('Exercice 4', 'Superman Dynamique', 2, '10'),
        ex('Exercice 5', 'Gainage Planche', 3, '30 sec'),
        ex('Exercice 5', 'Planche Haute Tap Épaules', 3, '30 sec'),
        ex('Exercice 5', 'Hollow Hold', 3, '30 sec'),
      ],
    },
  ];

  // Build At Home — phase 2
  const bahSessions2 = [
    {
      id: id(), name: 'Queen Of Glutes Débutante', duration: 35,
      description: 'Issu du Programme Maison Build At Home',
      objective: 'Tonification, Perte de Poids',
      muscles: ['Glutes', 'Bas du corps', 'Fessiers'],
      equipment: ['Bande de résistance', 'Haltère', 'Tapis de sol', 'Chaise'],
      exercises: [
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Deep Lunges Dynamiques', 1, '5', true),
        ex(WARM, 'Ouverture de Hanches', 1, '10', true),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '15'),
        ex(WARM, 'Glute Bridge - PDC', 1, '15'),
        ex('Exercice 1 - Superset', 'Hip Thrust Pause - PDC', 4, '10'),
        ex('Exercice 1 - Superset', 'Hip Thrust Hold - PDC', 4, '10 sec'),
        ex('Exercice 2', 'Romanian Deadlift Unilatéral - Haltère', 3, '8', true),
        ex('Exercice 3', 'Fentes Arrières Alternées - PDC', 3, '10', true),
        ex('Exercice 4 - Superset', 'Good Morning - PDC', 3, '10'),
        ex('Exercice 4 - Superset', 'Abductions Debout - Haltères', 3, '12', true),
        ex('Exercice 5', 'Glute Bridge - Bande de Résistance', 1, 'AMRAP'),
      ],
    },
    {
      id: id(), name: 'Upper & Core Power Débutante', duration: 40,
      description: 'Issu du Programme Maison Build At Home',
      objective: 'Force et Flexibilité',
      muscles: ['Haut du corps'],
      equipment: ['Haltère', 'Chaise', 'Tapis de sol'],
      exercises: [
        ex(WARM, 'Chien Tête En Bas Et Cobra Pose', 1, '5'),
        ex(WARM, 'Cat Cow', 1, '5'),
        ex(WARM, 'Around The World', 1, '10'),
        ex(WARM, 'Pull Apart', 1, '10'),
        ex('Exercice 1', 'Développé Épaules Unilatéral - Haltère', 3, '10', true),
        ex('Exercice 2 - Superset', 'Rowing Unilatéral - Haltère', 3, '10', true),
        ex('Exercice 2 - Superset', 'Pompes Inclinées', 3, 'AMRAP'),
        ex('Exercice 3 - Superset', 'Biceps Curl - Haltères', 3, '10'),
        ex('Exercice 3 - Superset', 'Oiseau - Haltères', 3, '8'),
        ex('Exercice 4', 'Dips sur Chaise - Jambes Pliées', 2, 'AMRAP'),
        ex('Exercice 5', 'Gainage Planche', 3, '30 sec'),
        ex('Exercice 5', 'Glute Bridge Marche - PDC', 3, '30 sec'),
        ex('Exercice 5', 'Hollow Crunch - Haltère', 3, '30 sec'),
        ex('Exercice 5', 'Hollow Hold', 3, '30 sec'),
      ],
    },
    {
      id: id(), name: 'Spicy Glutes Débutante', duration: 40,
      description: 'Issu du Programme Maison Build At Home',
      objective: 'Prise de Masse, Perte de Poids, Tonification',
      muscles: ['Fessiers'],
      equipment: ['Bande de résistance', 'Haltère', 'Chaise', 'Tapis de sol'],
      exercises: [
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Deep Lunges Dynamiques', 1, '5', true),
        ex(WARM, 'Ouverture de Hanches', 1, '10', true),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '15'),
        ex(WARM, 'Glute Bridge - PDC', 1, '15'),
        ex('Exercice 1', 'Sumo Squat en RDL - Haltère', 3, '10'),
        ex('Exercice 2', 'Hip Thrust Unilatéral - Haltère', 3, '8', true),
        ex('Exercice 3', 'Fentes Croisée Alternées - Haltères', 3, '20'),
        ex('Exercice 4', 'Fire Hydrant - Bande de Résistance', 2, '12', true),
        ex('Exercice 5 - Superset', 'Crab Walk - Bande de Résistance', 3, '20'),
        ex('Exercice 5 - Superset', 'Jump Squat', 3, '15'),
      ],
    },
    {
      id: id(), name: 'Strong Cardio Débutante', duration: 45,
      description: 'Issu du Programme Maison Build At Home',
      objective: 'Amélioration des Performances',
      muscles: ['Full body'],
      equipment: ['Tapis de sol'],
      exercises: [
        ex(WARM, 'Cat Cow', 1, '5'),
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '10'),
        ex('Exercice 1', 'Jump Squat Serré', 4, '30 sec'),
        ex('Exercice 1', 'Demi Burpees', 4, '30 sec'),
        ex('Exercice 1', 'Gainage Latéral Dynamique Gauche', 4, '30 sec'),
        ex('Exercice 1', 'Gainage Latéral Dynamique Droit', 4, '30 sec'),
        ex('Exercice 1', 'Montée de Genoux', 4, '30 sec'),
        ex('Exercice 1', 'Walk Out Planche et Mountain Climber', 4, '30 sec'),
        ex('Exercice 1', 'V Ups', 4, '30 sec'),
      ],
    },
    {
      id: id(), name: 'Full Body Energy Débutante', duration: 40,
      description: 'Issu du Programme Maison Build At Home',
      objective: 'Tonification, Perte de Poids',
      muscles: ['Full body'],
      equipment: ['Haltère', 'Tapis de sol'],
      exercises: [
        ex(WARM, 'Chien Tête En Bas Et Cobra Pose', 1, '5'),
        ex(WARM, 'Side to Side Reach', 1, '10'),
        ex(WARM, 'Around The World', 1, '10'),
        ex(WARM, 'Squat Profond et Extension de Genoux', 1, '10'),
        ex(WARM, 'Leg Swings Frontal', 1, '10', true),
        ex(WARM, 'Air Squat', 1, '10'),
        ex('Exercice 1', 'Fentes Arrières en Biceps Curl - Haltères', 3, '6', true),
        ex('Exercice 1', 'Développé Épaules Position Fentes - Haltères', 3, '6', true),
        ex('Exercice 1', 'Squat Hold', 3, '30 sec'),
        ex('Exercice 2', 'Romanian Deadlift en Équilibre - Haltère', 3, '8', true),
        ex('Exercice 2', 'Développé Couché Glute Bridge - Haltères', 3, '10'),
        ex('Exercice 2', 'Gainage Row - Haltères', 3, '8', true),
        ex('Exercice 3', 'Gainage Commando', 3, '30 sec'),
        ex('Exercice 3', 'Gainage Planche Twist', 3, '30 sec'),
        ex('Exercice 3', 'Reverse Planche', 3, '30 sec'),
        ex('Exercice 3', 'Reverse Planche Marche', 3, '30 sec'),
      ],
    },
  ];

  window.SEED_VERSION = 5;

  window.SEED_PROGRAMS = [{
    id: 'busygirl',
    name: 'Busy Girl',
    emoji: '👛',
    color: 0,
    description: '2 phases de 4 semaines · 4 séances par semaine',
    phases: [
      { name: 'Phase 1', weeks: 4, sessions },
      { name: 'Phase 2', weeks: 4, sessions: sessions2 },
    ],
  }, {
    id: 'buildathome',
    name: 'Build At Home',
    emoji: '🏠',
    color: 1,
    description: "Sculpte ton corps depuis ton salon, avec une paire d'haltères seulement. 8 semaines · 5 séances par semaine",
    phases: [
      { name: 'Phase 1', weeks: 4, sessions: bahSessions },
      { name: 'Phase 2', weeks: 4, sessions: bahSessions2 },
    ],
  }];
})();
